// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'worker.dart';

// These functions are ignored because they are not marked as `pub`: `build_render_config`, `map_query_rows`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Global init. `log_dir` is a writable directory for the log file.
Future<void> init({required String logDir}) =>
    RustLib.instance.api.crateFileInit(logDir: logDir);

/// Open a log file.  Loading happens on a background thread.
Future<void> openFile({required String path, BigInt? maxFileSize}) => RustLib
    .instance
    .api
    .crateFileOpenFile(path: path, maxFileSize: maxFileSize);

/// Poll the current loading status.
Future<FileStatus> getFileStatus() =>
    RustLib.instance.api.crateFileGetFileStatus();

/// Query logs with optional SQL filter / FTS search.
Future<Logs> getLogs({
  required String filterSql,
  required String ftsQuery,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateFileGetLogs(
  filterSql: filterSql,
  ftsQuery: ftsQuery,
  limit: limit,
  offset: offset,
);

/// Get the raw JSON text for one log entry.
Future<String?> getLogDetail({required int id}) =>
    RustLib.instance.api.crateFileGetLogDetail(id: id);

/// Get distinct values of a field (for autocomplete).
Future<List<String>> getFieldValues({
  required String field,
  required String search,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateFileGetFieldValues(
  field: field,
  search: search,
  limit: limit,
  offset: offset,
);

/// Load the render configuration from the embedded config file.
Future<RenderConfig> getRenderConfig() =>
    RustLib.instance.api.crateFileGetRenderConfig();

class Log {
  final int id;
  final Map<String, String> fields;
  final String? snippet;

  const Log({required this.id, required this.fields, this.snippet});

  @override
  int get hashCode => id.hashCode ^ fields.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Log &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fields == other.fields &&
          snippet == other.snippet;
}

class Logs {
  final List<Log> logs;
  final int totalCount;

  const Logs({required this.logs, required this.totalCount});

  @override
  int get hashCode => logs.hashCode ^ totalCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Logs &&
          runtimeType == other.runtimeType &&
          logs == other.logs &&
          totalCount == other.totalCount;
}

class RenderCell {
  final String? expr;
  final String? style;
  final int? maxLines;
  final bool? ellipsis;
  final String? tooltip;
  final List<RenderElement> elements;

  const RenderCell({
    this.expr,
    this.style,
    this.maxLines,
    this.ellipsis,
    this.tooltip,
    required this.elements,
  });

  @override
  int get hashCode =>
      expr.hashCode ^
      style.hashCode ^
      maxLines.hashCode ^
      ellipsis.hashCode ^
      tooltip.hashCode ^
      elements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderCell &&
          runtimeType == other.runtimeType &&
          expr == other.expr &&
          style == other.style &&
          maxLines == other.maxLines &&
          ellipsis == other.ellipsis &&
          tooltip == other.tooltip &&
          elements == other.elements;
}

class RenderColumn {
  final double? width;
  final int? flex;
  final String? align;
  final List<RenderCell> rows;

  const RenderColumn({this.width, this.flex, this.align, required this.rows});

  @override
  int get hashCode =>
      width.hashCode ^ flex.hashCode ^ align.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderColumn &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          flex == other.flex &&
          align == other.align &&
          rows == other.rows;
}

class RenderConfig {
  final List<RenderColumn> columns;
  final List<String> fields;

  const RenderConfig({required this.columns, required this.fields});

  @override
  int get hashCode => columns.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderConfig &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          fields == other.fields;
}

class RenderElement {
  final String expr;
  final String? style;
  final String? tooltip;

  const RenderElement({required this.expr, this.style, this.tooltip});

  @override
  int get hashCode => expr.hashCode ^ style.hashCode ^ tooltip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderElement &&
          runtimeType == other.runtimeType &&
          expr == other.expr &&
          style == other.style &&
          tooltip == other.tooltip;
}
