// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'worker.freezed.dart';

@freezed
sealed class FileStatus with _$FileStatus {
  const FileStatus._();

  const factory FileStatus.uninit() = FileStatus_Uninit;
  const factory FileStatus.loading({
    required String phase,
    required double progress,
    required BigInt loadedCount,
  }) = FileStatus_Loading;
  const factory FileStatus.complete({
    required BigInt totalCount,
    required bool truncated,
  }) = FileStatus_Complete;
  const factory FileStatus.error(String field0) = FileStatus_Error;
}
