// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LogState`

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Open a file and build the line index.
/// This might take a few seconds for very large files.
Future<BigInt> openFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleOpenFile(path: path);

/// Get the total number of lines in the currently opened file
Future<BigInt> getTotalLines() =>
    RustLib.instance.api.crateApiSimpleGetTotalLines();

/// Read a specific range of lines
Future<List<String>> readLines({
  required BigInt startLineIndex,
  required BigInt count,
}) => RustLib.instance.api.crateApiSimpleReadLines(
  startLineIndex: startLineIndex,
  count: count,
);
